### ISSUE TITLE
Refresh page for operational tv

### ISSUE THREAD

**Issue by NargiT** [PagerDuty/pd-live-react#393]
Hello,

Is it possible to have a configurable refresh of the page in order to get alerts. From my experience it does not refresh.

**Comment by gsreynolds** [comment]
Hi @NargiT - the PD Live console is designed to be real-time and will fetch updates every 5 seconds, which is not configurable. You don't need to refresh the page for recent incidents/alerts.

Can I ask, are you using the GitHub pages hosted version at https://pagerduty.github.io/pd-live-react/ ? Do you see a Green connection icon top right in the PD Live UI?

![Screenshot 2024-01-26 at 13 34 30](https://github.com/PagerDuty/pd-live-react/assets/1533562/38ff6159-9480-4753-8e03-8b576e9280c0)

**Comment by gsreynolds** [comment]
@NargiT The GitHub Pages hosted version will work with any PagerDuty subdomain. If you are self-hosting the React project your subdomain will not have the required ability, so you will need to review the settings in https://github.com/PagerDuty/pd-live-react/blob/main/src/config/constants.js.

**Comment by gsreynolds** [comment]
@NargiT - please force refresh https://pagerduty.github.io/pd-live-react/. The ability check for GitHub Pages was not overridden correctly in the GitHub Actions build process.

Thanks for bringing this to our attention. Please confirm this has resolved the issue for you.
